### ISSUE TITLE
Nerodo nauju missed jei toks senas netatskambintas

### ISSUE THREAD

**Issue by rgricius** [tenesys-software/MissedCallsCore#4]
Nerodo nauju missed jei toks senas netatskambintas
Pvz. 861158866 skmbino sian i vip eile 811 ir buvo praleistas tai jo neroro praleistu 1 lenteleje nerodo jeigu sis numeris skambino ansciau ir buvo praleistas anksciau nei pagal pasirinkta diena t.y. siandien.

Detalioje ataskaitoje jeigu pasirenki platesni datu filtra 
861158866 | 811 (3) | VIP eile | 2018-07-27 09:43:59 | 04.10:15:29

**Comment by pupultukas** [comment]
Reikia gaudyti toliau, nes man rodo
![capture1](https://user-images.githubusercontent.com/25983018/43577632-0b28650a-9655-11e8-87fd-56740ec4e891.PNG)
![capture2](https://user-images.githubusercontent.com/25983018/43577633-0b43860a-9655-11e8-9853-75feec0fbf8e.PNG)
